### ISSUE TITLE
Doesn't Start On My Machine.

### ISSUE THREAD

**Issue by MohsenDehbag** [shynvn/fa-docs#1]
Hey, I tried to run it On Two Devices with different operating Systems and I got the same output. Did I forget sth?

[2020-07-22T18_24_26_997Z-debug.log](https://github.com/shynvn/fa-docs/files/4962052/2020-07-22T18_24_26_997Z-debug.log)
[Terminal Log](https://github.com/shynvn/fa-docs/files/4962053/Terminal.Log)

**Comment by shynvn** [comment]
Hey there, You need to run ```npm install``` after cloning the repository to download and install dependencies (you only need to do this once).
After that Use ```npm start``` everytime you want to run the project
I've updated README.md to prevent these kind of problems in the future
